(define (problem run-generator2)
    (:domain generator)
    (:objects gen - generator tank1 tank2 - tank)
    (:init 	(= (fuelLevel gen)  40)
		(= (capacity gen)  900)
		(available tank1)
		(available tank2)		
     )  
     (:goal (generator-ran))
) 
