(define (problem tank-problem)
(:domain tank-domain)
(:objects tank1 tank2 - tank bucket1 - bucket)
(:init (= (volumebuck bucket1) 0)
  (= (capacity bucket1) 60)
  (= (volumetank tank1) 100)
  (= (sqrtvolinit tank1) 10)
  (= (flow-constant tank1) 0.8)
  (= (volumetank tank2) 64)
  (= (sqrtvolinit tank2) 8)
  (= (flow-constant tank2) 1))
(:goal (> (volumebuck bucket1) (- (capacity bucket1) 2)))
(:metric minimize (total-time))) 